name: 08 - Using variables

on:
  workflow_dispatch:

env:
  WORKFLOW_VAR: "I am a workflow env var"
  MY_OVERWRITTEN_VAR: "I will be overwritten"

jobs:
  echo:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: "I am a job env var"
      OVERWRITTEN: "I have been overwritten at the job level"
    steps:
      - name: "Print env variables"
        env:
          STEP_VAR: "I am step env var"
          step_var2: "I am another step var"
        run: |
          echo "Step env var: $STEP_VAR"
          echo "Step env var 2: $step_var2"
          echo "Job env var: $JOB_VAR"
          echo "Overwritten: $OVERWRITTEN"

      - name: "Overwrite Job variable"
        env:
          OVERWRITTEN: "I have been overwritten at the step level"
        run: |
          echo "Step env var: $OVERWRITTEN"
